cargo-features = ["edition"]

[package]
name = "slablit"
description = "Literal for slab creation"
version = "0.2.0"
authors = ["Ruben Schmidmeister <ruben@myelin.ch>"]
edition = "2018"

[dependencies]
slab = "0.4"
