cargo-features = ["edition"]

[package]
name = "slablit"
description = "Literal for slab creation"
version = "0.2.0"
authors = ["Ruben Schmidmeister <ruben@myelin.ch>"]
license = "MIT/Apache-2.0"
readme = "readme.md"
repository = "https://github.com/myelin-ai/slablit"
homepage = "https://github.com/myelin-ai/slablit"
documentation = "https://docs.rs/slablit"
edition = "2018"

[dependencies]
slab = "0.4"

[badges]
travis-ci = { repository = "myelin-ai/slablit", branch = "master" }
